version: "3.3"

services:

  oscb_mysql:
    container_name: oscb_mysql_container
    image: oscb_mysql
    build:
      context: ./ai-single-cell-mysql
    volumes:
        - ./mysql_db:/var/lib/mysql
    command:
        [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password",
        ]
    env_file:
        - .env  
    networks:
      - ai-single-cell

      # Cache
  # cache:
  #     container_name: oscb_cache_container
  #     image: redis:7.0-alpine
  #     networks:
  #       - ai-single-cell

  oscb_node:
    container_name: oscb_node_container
    image: oscb_node
    build:
      context: ./ai-single-cell-node
    ports:
      - "3001:3001"
      - "3020:3020"
    environment:
      - EXTERNAL_PORT=3001
      - DBUSER=root
      - DBPASSWORD=Shirley@2410
      - DATABASE=aisinglecell
      - HOST=oscb_mysql # NAME OF THE SERVICE
      - HOST_URL=${HOST}
      - SSH_CONNECTION=${SSH_CONNECTION}
    depends_on:
      - oscb_mysql
    volumes:
      - user_storage:/usr/src/app/storage/
    networks:
      - ai-single-cell

  oscb_react:
    container_name: oscb_react_container
    image: oscb_react
    build: ./ai-single-cell-react
    ports:
      - "3000:3000"
    depends_on:
      - oscb_node
    environment:
      - HOST_URL=${HOST}
    networks:
      - ai-single-cell

  directus:
    container_name: oscb_directus_container
    image: directus/directus:9.24.0
    restart: unless-stopped
    ports:
        - 8055:8055
    volumes:
        - ./uploads:/directus/uploads
    depends_on:
        - oscb_mysql
    env_file:
        - .env
    networks:
      - ai-single-cell
  
  oscb_flask:
    build:
      context: ./ai-single-cell-flask
      dockerfile: Dockerfile
    container_name: oscb_flask_container
    image: oscb_flask
    restart: always
    ports:
      - "5000:5000"
    networks:
      - ai-single-cell
    volumes:
      - user_storage:/usr/src/app/storage/

volumes:
  user_storage: {}

networks:
  ai-single-cell:
  
